### PR TITLE
Angular 7 compatibility and cleanup

### PR DESCRIPTION
**Pull request by guillaume-ro-fr**
- Angular 7 compatibility
- Remove `dist` folder (or remove the entry in the `.gitignore` file)
- Remove generated Angular files (`*.d.ts`, `*.js`, `*.js.map`, `*.metadata.json`)
- Remove `node_folder` (or remove the entry in the `.gitignore` file)

### CODE REVIEW

**Comment by web-dave** [comment]
Hmm, I still try to get this running. Have some weird issues. I keep on fighting.
My idea is to switch to Angular CLI and generate a library.

**Comment by MikaStark** [comment]
Looking forward for this fix ^^

**Comment by RJiryes** [comment]
Hey, any updates on this?

**Comment by mhosman** [comment]
When you're gonna merge this???

**Comment by sketchthat** [comment]
If you can't wait for this to be merged (As it has been ~5 months since last comment from the owner) you can install straight from the fork `npm install guillaume-ro-fr/ngx-img-cropper#master`

**Comment by mhosman** [comment]
Great @sketchthat! It seems that this repository has been abandoned

**Comment by guillaume-ro-fr** [comment]
@mhosman You can use the pre-release with the build package to avoid an Typescript error with Angular (`The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library.`) : 

`package.json` : 
```json
"dependencies": {
...
    "ngx-img-cropper": "https://github.com/guillaume-ro-fr/ngx-img-cropper/releases/download/0.11.0/ngx-img-cropper-0.11.0.tgz"
...
}
```

**Comment by nimatullah** [comment]
Guys, please merge this pull request.

**Pull request merged**
